name: Go App Engine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: your-project-id

    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure gcloud CLI
      run: |
        gcloud config set project your-project-id
        gcloud config set app/cloud_build_timeout 1600

    - name: Install and configure the App Engine component
      run: gcloud components install app-engine-python

    - name: Build and Deploy
      run: |
        cd ./
        gcloud app deploy app.yaml --promote --stop-previous-version

    - name: Show Deployment Information
      run: |
        gcloud app browse
